language: python
python:
    - "3.6"

sudo: true  # Needed for coreir-dev branch building coreir from source (installing g++-4.9 through apt)

before_install:
    - source .travis/install_coreir.sh

install:
    - pip install -r requirements.txt
    - pip install pytest-cov delegator.py
    - pip install -e .

script:
    - py.test --cov=magma tests/
